[package]
name = "othello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tui-big-text = "0.7.1"
